### ISSUE TITLE
x1.1.delta: Rdf Relation: Contract bindsBuyer Buyer

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#101]
If joint procurement is concerned then all Buyers may or may not be jointly responsible for a given procedure and may or may not be bound by a contract.  However in a notice we do not know to which extent  a Buyer is involved in a joint procurement.  Therefore we cannnot assume "Contract bindsBuyer" is correct the only thing we can assume is that the Procedure involves all the Buyers.

An example of Contract bindsBuyer can be seen in notice 2705-2021.

Therefore it seems this relation is inappropriate in the rdf

**Comment by costezki** [comment]
We will not relate the contract and buyer. 

The existent mapping rules shall be commented out but not deleted. 

![image](https://user-images.githubusercontent.com/13567133/188911036-31f75443-fbfe-4ed4-93b9-e6a185cbef1c.png)
![image](https://user-images.githubusercontent.com/13567133/188911428-f75bfec5-a8e7-441f-a65d-772909ebf49c.png)

**Comment by fokoug** [comment]
I put all rr:predicateObjectMap in comment. File S5_award_of_contract.rml.ttl

**Comment by csnyulas** [comment]
Reopening this issue, as it seems like we failed to comment out one of the predicate-object maps in [s5_award_of_contract.rml.ttl](https://github.com/OP-TED/ted-rdf-mapping/commit/f65974ef03c819b406ba69ee11542e93512d6433#diff-a22efb2c13b4a01884dccfabdb440ac9144639212fbe602e97c4debfa0c72a2f), which creates a `bindsBuyer` relationship in certain cases, as illustrated below:
![image](https://user-images.githubusercontent.com/2441046/192392110-ebb4450c-642c-44d8-bfb8-9434cffd29b4.png)

@costezki and/or @idellal can you confirm that we should have commented out also the fourth predicate-object map referring to `bindsBuyer` ?

See also this comment on the "fixing" commit: https://github.com/OP-TED/ted-rdf-mapping/commit/f65974ef03c819b406ba69ee11542e93512d6433#r85085394

**Comment by costezki** [comment]
Yes, I confirm. We shall not use this relation in the standard notices.

**Comment by csnyulas** [comment]
This was fixed in commits:
https://github.com/OP-TED/ted-rdf-mapping/commit/f65974ef03c819b406ba69ee11542e93512d6433#diff-a22efb2c13b4a01884dccfabdb440ac9144639212fbe602e97c4debfa0c72a2f
https://github.com/OP-TED/ted-rdf-mapping/commit/74b8ba23c34b1686aed164a4aeb93256840c3578#diff-67d27807b5b8cd9eb947bccd21b0f53b243e3617efa5a5d2a05d1f873afb4ed0 , and
https://github.com/OP-TED/ted-rdf-mapping/commit/43069749d9c6564d247616138f44950ca7962e33#diff-67d27807b5b8cd9eb947bccd21b0f53b243e3617efa5a5d2a05d1f873afb4ed0 

Running the following SPARQL query will return no values now (but was returning 109 results on the data generated from tag `tx1.1.delta`):
```SPARQL
SELECT ?s ?p ?o 
{ ?s epo:bindsBuyer ?o . }
```
