### ISSUE TITLE
tx1.1.delta: Conceptual Mappings: Section V.2.4.2 Total value of the contract/lot

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#127]
Is this correct to map to the tender for example in the case of a negotiated procedure

**Comment by csnyulas** [comment]
I assume this is about V.2.4, not II.2.4, as it says currently in the title.

**Comment by costezki** [comment]
We can discuss this in the ontology meetings.

**Comment by costezki** [comment]
1. 
The suggestion is to switch (for field V.2.4.2) *Tender -> hasFinancialOfferValue -> MonetaryValue* to *LotAwardOutcome -> hasAwardedValue -> MonetaryValue*. The later is already used to map field V.2.6.1 (used in F06). 

If we do this switch, both values will be mapped to *LotAwardOutcome -> hasAwardedValue -> MonetaryValue*, hence leading, in some cases, to TWO MonetaryValues for the LotAward outcome, and their origin will not be traceable (i.e. whether they come from the field V.2.4.2, or V.2.6.1).

![image](https://user-images.githubusercontent.com/13567133/199198470-179e3a4b-b7ce-4baa-9b4e-b4a384a91ba3.png)

![image](https://user-images.githubusercontent.com/13567133/199197854-640b09a9-7df9-4dd8-a908-2d7f42da7cd2.png)

2. Also, where shall we use the property *Tender -> hasFinancialOfferValue -> MonetaryValue* ???

**Comment by muricna** [comment]
Another predicate is required for Bargain purchases as these are not the total awarded value.

**Comment by costezki** [comment]
A new relation has been added "epo:hasBargainPrice"

The mappings change:
V.2.4.2 === LotAwardOutcome -> hasAwardedValue -> MonetaryValue
V.2.6.1 === LotAwardOutcome -> hasBargainPrice -> MonetaryValue
*NOT used* === Tender -> hasFinancialOfferValue -> MonetaryValue


![image](https://user-images.githubusercontent.com/13567133/199758595-fc91d40e-98b2-4912-8d6e-ec1eaedeacb7.png)

**Comment by csnyulas** [comment]
Issue has been fixed in commits https://github.com/OP-TED/ted-rdf-mapping/commit/50e1b469de08be3c424d11da64f6d7f62894bd6c and https://github.com/OP-TED/ted-rdf-mapping/commit/30b052c4ff3ff6755c5ce54ab7406b356e9c8dd8 .

As it can be seen by looking at the changes in the generated `.ttl` files (such as https://github.com/OP-TED/ted-rdf-mapping/commit/30b052c4ff3ff6755c5ce54ab7406b356e9c8dd8#diff-97c948015adfe05ab4ac84d2889329672927870ee359021bb306b6db33ff75e6 or https://github.com/OP-TED/ted-rdf-mapping/commit/30b052c4ff3ff6755c5ce54ab7406b356e9c8dd8#diff-588d976f3db567ed7e513bb907f0dc41c5c58050cf2b92f43bc7c3b6c96d6fe6 or https://github.com/OP-TED/ted-rdf-mapping/commit/30b052c4ff3ff6755c5ce54ab7406b356e9c8dd8#diff-69f84aa5f6b9e901f1fd9b624b480a950928d2aef0f19d2231d2a944b8ab0af4), the fix has the desired effect. 
The validation reports did not introduce any further problems either, so we can close this (and the related #113) issue.
