### ISSUE TITLE
tx1.1.delta: Conceptual Mappings: Section VI.V.1 Reviewer, mediator, ReviewProcedureInformationProvider

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#128]
The xml does not foresee an indentifier for the Review body, however the rdf foresees and idenfier and copies the name of the reviewer into the identifier there should be no identifier see348503-2021
The same for Mediator and ReviweProcedureInformationProvider see 56148-202&

**Comment by csnyulas** [comment]
The generated RDF follows the ePO model, where *every* organization, regarding of what role they play, should have an ID (of type `epo:Identifier` that is linked by the `epo:hasId` property). This identifier normally should have a specific value specified using the `epo:hasIdentifierValue`. We use the `NATIONALID` XML element to generate a value for this Identifier instances. According to the the XSD, this XML element is available for all "contact information" elements, including for `ADDRESS_CONTRACTING_BODY`, `ADDRESS_REVIEW_BODY`, `ADDRESS_MEDIATION_BODY`, `ADDRESS_REVIEW_INFO`, etc. However, it is true that because the PDF form does not allow the specification of this information in section 6, this will not likely to appear in the XML form data.

The question is: 
How should we deal with the creation of the `Identifier`s when no `NATIONALID` element is specified in the XML? 
Should we create an "empty" instance of `epo:Identifier`, which does not have an `epo:hasIdentifierValue` property attached?
Would it be OK to use the `OFFICIALNAME` of the organization, as the identifier value? (this is what is happening now in certain cases that were identified in this ticket, and I assume is not OK)
Can we have an organization that has no identifier attached (i.e. it has no `hasId` property)?
What else can we do?

**Comment by costezki** [comment]
Do not create am epo:Identifier instance for any organisation that has no ID (e.g. national ID); including Mediator, ReviweProcedureInformationProvider, or Review body.

**Comment by csnyulas** [comment]
Please double check that Identifier instances are not critical (i.e. they are not referenced by anyone other than the organization that they define), and removing them won't break anything.
