### ISSUE TITLE
tx1.1.delta: Conceptual Mappings: Section 1.4 Buyer Legal Type missing 19698-2021

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#133]
missing  buyer-legal- tupe19698-2021: The concept in the xml is "other" which is not in the authority table buyer-legal-type.  Therefore there should also be a description which is not foreseen in the ontology

What is more the ontology states Organization hasLegalType and the mapping hasBuyerType so there are inconsitencies where the mappings exist.

Also the authority table is floating in some of the diagrams of the ontology

The buyer-legal-type mapping in resources does not foresee the xml element "other"

**Comment by muricna** [comment]
Main activity would seem to have the same problem

**Comment by costezki** [comment]
"other" needs to be discussed, what shall it be mapped to. It is also *outside* the mapping resource `buyer_legal_type.csv`. 
![image](https://user-images.githubusercontent.com/13567133/188606775-1ac8e06e-47a2-4771-be45-2d68b42aaf3e.png)

The buyer-legal-type mapping *cannnot* and *should not* foresee "other" because in the XML it is represented as an element and NOT a value. 

We can also discuss this in the ontology meetings.

**Comment by csnyulas** [comment]
This issue is broken done, and will be handled in issues #198, #199 and #200.
