### ISSUE TITLE
tx1.1.delta: Section V: Non Award of Contract but Contract number and Title provided in xml

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#140]
The xml shows a contract number in the xml however no contract was awarded.  The contract number is not provided in the rdf however the rdf is supposed to represent the xml should such corrections be made to follow the ontology?
See 131568-2021 Lots 4 and 5
This also means we are missing the tiel in teh these sections too

**Comment by fokoug** [comment]
Here is the conceptual mapping:
![Screenshot 2022-09-06 at 01 18 15](https://user-images.githubusercontent.com/24571803/188520342-c65f891e-b0bf-4076-8dbb-c3fa38dbd847.png)
When a contract is not awarded only contract and buyer instance are created. The contract number  is always mapped.
Here is an screenshot of example of  award contract from 131568-2021.xml file (Lots 4 and 5).
![Screenshot 2022-09-06 at 01 29 41](https://user-images.githubusercontent.com/24571803/188520576-19590bf7-c97c-4ffe-9fdd-bb12c9f03cd6.png)
Here is the corresponding mapping of Contract and Contract N°:
![Screenshot 2022-09-06 at 01 33 07](https://user-images.githubusercontent.com/24571803/188520699-44b54be8-3736-478f-8014-385f068951f8.png)
![Screenshot 2022-09-06 at 01 33 39](https://user-images.githubusercontent.com/24571803/188520704-bfa95cc4-686d-42a0-a445-9a91b50053ef.png)
And below the result rdf data:
![Screenshot 2022-09-06 at 01 35 43](https://user-images.githubusercontent.com/24571803/188520781-b0bf9421-64e9-4ac8-a67c-8a14263ff3cf.png)
![Screenshot 2022-09-06 at 01 36 01](https://user-images.githubusercontent.com/24571803/188520790-be907814-8975-45c9-bf49-9b649a387473.png)
We could observe that for **"Startup in Residence bij EZK/LNV 2020"** (the second), instead of the contract number as Identifier, we got the Item rank. That means we need to look the contract number mapping, mainly the condition **if (exists(CONTRACT_NO) and exists(AWARDED_CONTRACT))** because this condition means that Contract number is mapped only for **AWARDED_CONTRACT**.

**Comment by costezki** [comment]
We have decided in a common meeting to do so - represent only awarded contracts. 
We can re-discuss in the ontology meetings what to do with the information on non-awarded contracts.

**Comment by costezki** [comment]
We can create new mappings fotr the new properties that have been added to the `epo:LotAwardOutcome`.
![image](https://user-images.githubusercontent.com/13567133/188659845-ee0d0592-840a-4a76-9b55-5b643406ed72.png)

**Comment by csnyulas** [comment]
Closing this issue as it has been fixed both in the technical mapping (see referenced commits above), and in the conceptual mapping (v6.7.0), where we added two new rows for the fields `V.0.1` (XPath `AWARD_CONTRACT/CONTRACT_NO`) and `V.0.3` (XPath `AWARD_CONTRACT/TITLE`), for the cases when the `NO_AWARDED_CONTRACT` XML element is present.
