### ISSUE TITLE
Make SPARQL query different using rdf:type triple pattern

### ISSUE THREAD

**Issue by fokoug** [OP-TED/ted-rdf-mapping#174]
Sometime, for different mapping rule we get same triple pattern in conceptual mapping like ?this epo:refersToRole ?value for I.1 (contracting authority ) and I.1 (additional). This way creates a warning in SPARQL report because a XML path could be not covered but SPARQL query return true since it is provide by another rule. 

We have to make the triple pattern more precise by adding rdf:type inside. We could use the beginning and ending classes in class path.

**Comment by csnyulas** [comment]
We close this issue as we have resolved this problem by adding `rdf:type` restrictions to the `?this` variable when we generate the validation SPARQL queries.

The algorithm could be improved to add type information also for the `?value` variable, but **only in certain circumstances**, because (as we have seen it) over-constraining it, would lead to a large number of invalid query results.
