### ISSUE TITLE
tx1-2: Mapping suite metadata: ontology version

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#236]
[N Muric - 2022-11-22]

> The metadata sheet of the conceptual mapping of the four forms indicate the mapping is to EPO
> version 3.0.0, however this does not seem to be the case. It is expected that the mappings are to a given release of the ontology. Corrections to the ontology were made in version 3.1.0 of the
> Ontology to accommodate the mapping it is not clear why this version was not used. 
> Where  updates to the ontology are required for the mappings, changes to the ontology should be requested immediately so that the ontology can be updated for the mapping. To this end where is the version of the ontology mentioned in the technical mappings?
>

**Comment by costezki** [comment]
The version of the ontology to which the mappings are done is indeed a moving target and shall be agreed upon in advance before the work begins.

Currently, the mappings are done to a future release because EPO does not satisfy all the needs of the Standard Forms. 
We can refer to it as to a future release (as of today) `3.1.0-dev` (to be read the development version of the 3.1.0) because then `3.1.0` is to be released in December 2022.

In the future, to avoid such situations we propose to perform mappings only to released versions of the ontology and split the work as follows:
1. perform the mapping in good faith and to the best of our understanding, to a fixed version of the ontology even if it may be incomplete or not conceptually correct (due to missing elements in the ontology) (initial order).
2. identify what ontology evolutions are necessary and implement them (in a separate order, i.e. EPO project)
3. upgrade the mappings from one version of the ontology to the newly released one (in a separate order).

**Comment by csnyulas** [comment]
Closing this ticket as this has been fixed in the Metadata sheet of the Conceptual Mapping files as proposed above. We also agreed that in the future we will create the mapping to beforehand agreed (and preferable published) versions of ePO, to avoid the "moving target" problem. This may come with other problems, though, namely, that  certain mappings will not be final, or even possible, at the time of the delivery, but be adjusted/provided at a later date, when the necessary changes that provide the appropriate representations were added to ePO.
