### ISSUE TITLE
tx1-2: Award under DPS and FA techniques (procedure / sub-procedure)

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#237]
[N Muric]
> In the contract award notices when Dynamic Purchasing systems and the resulting contracts of
> Framework Agreements are being mapped and there are problems. The award award and submission statistical information are being mapped via lots, however in these cases lots are not concerned.
> Any correction to this will depend on an update to the ontology.
>

**Comment by costezki** [comment]
Ontology updates will have to be done first before we address this issue. 

See https://github.com/OP-TED/ePO/issues/416

**Comment by andreea-pasare** [comment]
As a temporary fix we connect SubmissionStatisticalInformation to LotAwardOutcome through epo:summarisesInformationForLotAwardOutcome:
![image](https://user-images.githubusercontent.com/88081600/204583330-cda4bbff-f9e7-49aa-b679-696d58dc1107.png)
This relation is replace epo:concernsSubmissionsForLot, that was between SubmissionStatisticalInformation and Lot.

**Comment by csnyulas** [comment]
The temporary solution (of linking SubmissionStatisticalInformation to LotAwardOutcome, through the epo:summarisesInformationForLotAwardOutcome property) has been implemented. This is in line with ePO v3.1.0.

However, to fully fix this issue, and be able to close it, we need further discussions and changes to ePO.

**Comment by muricna** [comment]
The temporary solution has been implemented in the ontology however it has not been reflected in the mappings.
Concerns sections: V.2.2 and V.2.4.3

**Comment by csnyulas** [comment]
The temporary solution has been implemented in tx1.3 release, and can be seen also in the latest tx1.4-beta release. It is implemented in the Conceptual mapping, the technical mapping, and we even have extra validation SPARQL queries implemented for this issue.

![image](https://user-images.githubusercontent.com/2441046/219683693-e63e8ef5-81f8-4343-aa3e-8b849588ecee.png)


![image](https://user-images.githubusercontent.com/2441046/219685873-91c4d830-7f5c-4851-8beb-ea1601bfad3c.png)


Current output for notice `580342-2021` (each `epo:SubmissionStatisticalInformation` instance is linked to only one LotAwardOutcome)
![image](https://user-images.githubusercontent.com/2441046/219684358-90305b1a-6d84-48e6-9ac7-1eeafc28ba62.png)

SPARQL validation query:
https://github.com/OP-TED/ted-rdf-mapping/blob/main/src/validation/sparql/iss_gh_map237_submissionStatInfo_relations.ask.rq

The only reason we haven't closed this ticket because we are waiting for the definitive EPO model, to update our solution.
