### ISSUE TITLE
tx1-2: procedure type missing in the output 

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#242]
Investigate for F06

> 10106-2021, 18749-2021, 269342-2021, 28796-2021, 327079-2021 and 352025-2021 do not have procedure-type should be negotiated with prior call

![image](https://user-images.githubusercontent.com/13567133/203523864-12373bbf-4932-454c-92f2-9f9672b80e13.png)
![image](https://user-images.githubusercontent.com/13567133/203523945-785f3dc4-101e-432f-873e-3ac09cc50316.png)

**Comment by fokoug** [comment]
In F06_2014.xsd we have
![Screenshot 2022-11-23 at 22 45 29](https://user-images.githubusercontent.com/24571803/203651546-b0ec91db-8526-489d-aa30-e76f5777b491.png)
but in the technical mapping instead of tag PT_NEGOTIATED_WITH_PRIOR_CALL we found
![Screenshot 2022-11-23 at 22 45 43](https://user-images.githubusercontent.com/24571803/203651668-d3dd242e-3d20-4540-862b-ca893e5ef926.png)
So we change the technical mapping.

**Comment by csnyulas** [comment]
First attempt for fixin this is in the commit: https://github.com/OP-TED/ted-rdf-mapping/commit/3c876b2f249d4cd1b8acceb28485b124b4ac2632
However, as pointed out in this comment https://github.com/OP-TED/ted-rdf-mapping/commit/3c876b2f249d4cd1b8acceb28485b124b4ac2632#r90930207, we probably need to keep the handling of the `PT_COMPETITIVE_NEGOTIATION` XML element as well, as it is was added as it is needed by a different form.

**Comment by fokoug** [comment]
PT_COMPETITIVE_NEGOTIATION added.
![Screenshot 2022-11-25 at 12 14 24](https://user-images.githubusercontent.com/24571803/203974019-066e51d4-f355-4b33-98f7-219ace9beec6.png)

**Comment by csnyulas** [comment]
See another related commit https://github.com/OP-TED/ted-rdf-mapping/commit/7388b51092ba3f1d91e02a859a92fe1d539d2b31

**Comment by muricna** [comment]
Please note Negotiated with prior publication of a call for competition and competitive with negotiation map to the same code neg-w-call:

![image](https://user-images.githubusercontent.com/26601116/208916226-9379bbb9-0080-41a7-93f8-39d95b5609b6.png)
