### ISSUE TITLE
tx1-2: handling boolean indicators 

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#246]
> V.2.9 The xml does not foresee a value however for either true or false but the rdf shows a  false variant value but the rdf does  389779-2001

Action: we will handle 3 variants: if value exists, the output will reflect the value (true/false) if missing, no output will be generated.

![image](https://user-images.githubusercontent.com/13567133/203538638-996d763b-17c9-4d42-8741-ea248e660703.png)

**Comment by fokoug** [comment]
There are many confusion with this field .
1 - In F06 the tag ACCELERATED_PROC doesn't appear in any of the input data file. 
2 -  In F06_2014.xsd the tag ACCELERATED_PROC doesn't appear (it is not in the XML structure) 
![Screenshot 2022-11-23 at 21 55 55](https://user-images.githubusercontent.com/24571803/203644578-3fb38559-424d-441b-8af9-841a441a44e1.png)
 It is for this reason in rdf file we always have a false for the predicate isAccelerated

1 - In F03 input data, it appears but it is not a boolean so we couldn't map to true and false. 
![Screenshot 2022-11-23 at 21 58 25](https://user-images.githubusercontent.com/24571803/203644988-75268f42-d5ec-495d-ac72-95c70ff2a04e.png)

2 - In F03_2014.xsd the tag ACCELERATED_PROC appears and it is  mapped as previously.
![Screenshot 2022-11-23 at 21 59 40](https://user-images.githubusercontent.com/24571803/203645347-413a67a8-8046-496f-a1a8-7e48349dae5c.png)

So, I propose :
 1 - put true if exist tag ACCELERATED_PROC and null otherwise (the one implemented for the moment)
 2 - if not exist ACCELERATED_PROC put null otherwise, if exist /P put true else put false.

**Comment by csnyulas** [comment]
Closing issues at it can be see that the recent outputs are correct (see above commits referencing this issue). Also it can be seen in this commit of the generated output:
https://github.com/OP-TED/ted-rdf-mapping/commit/982be7a9cccf2f9a5b9a37489d465f4af3afb801#diff-c804db56d98d4bffbf1976f88bf1fce3d135398c8691c0ff5743d561014988f6
