### ISSUE TITLE
add new code values into the mappings: rejection and none-receipt

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#247]
[N Muric] comments on F06 in TX1-2

> V.1.1.1 waiting new code list from EU Vocabularies to cover rejection and none-receipt

**Comment by csnyulas** [comment]
The new value that is to be used for mapping field V.1.1.1 is:
http://publications.europa.eu/resource/authority/non-award-justification/none-rej
(instead of http://publications.europa.eu/resource/authority/non-award-justification/all-rej)

Note: The term has been created in the vocabulary, and it is to be published soon.

**Comment by csnyulas** [comment]
Conceptual mapping was adjusted starting with version 4.1.0

**Comment by csnyulas** [comment]
Closing this issue as it was fixed. See references from commits above.
