### ISSUE TITLE
tx1-2: fileds that may appear in multiple notice type (e.g. estimated date of publication)

### ISSUE THREAD

**Issue by costezki** [OP-TED/ted-rdf-mapping#249]
[N Muric] F21 context
> II.3 This field is only used for Prior information Notice to show the estimated date of Publication of the Contract Notice and not the date of publication of the Result notice as shown in the mapping.

Answer: A simple solution is to map this field to epo:Notice because only contract notices and PINs may have such field, and thus only on those cases the mapping will be activated. 

> IV2.1 This field can also be used for calls for competition so going through the ResultNotice does not always work.  See 459484-2021

Anser: idem

**Comment by csnyulas** [comment]
This should be handled when we fix #238

**Comment by csnyulas** [comment]
The conceptual mapping aspects of this issue is handled in version 5.0.1 of the CM, and the technical mapping is also done (see the commits referencing this issue), however there is an outstanding question for the first problem mentioned in this issue for which we created a separate issue (#262). So, we will mark this issue fixed and will close it.
