### ISSUE TITLE
II.1.6.1 Xpath is missing

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#302]
Xpath is missing and a reference made in the notes to the remarks page in F22.  See also issue 191 for similar but different problem in F25.  Other forms should be checked.

**Comment by csnyulas** [comment]
We included a Note, to reference the "Mapping Remarks" sheet, where we explain why we don't have a mapping for this field (CM version 6.8.0).

We are not providing an XPATH in the "Rules" sheet, as not to generate unnecessary SPARQL queries (or to avoid failure of generating "empty" SPARQL queries). Despite of this, it is important to mention this field in the "Rules" sheet, especially for forms F21, F22 and F23 (which is what we did before), because in those forms this field has several sub-fields, as well (`II.1.6.1.1`, `II.1.6.1.2`, `II.1.6.1.3`), and mentioning `II.1.6.1` (although that, itself, is not mapped), it puts the sub-fields in context.

To make the CM consistent among the various forms, we now included field `II.1.6.1` (with the appropriate reference note to the "Mapping Remarks" sheet), also for forms F03, F06 and F25.

I will mark this issue "act:for closing", and will close it soon, unless there are objections to the implemented solutions.
