### ISSUE TITLE
Repeated instantiations of concepts

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#314]
Examples:

See F22:

II.2.7.2 defines ContractPeriod hasBeginning exists in each lot as many times as there are lots instead of once for each lot see 309436-2021 (15 lots each lot has 15 contract periods)

II.2.7.3 defines ContractPeriod hasEnd exists in each lot as many times as there are lots instead of once for each lot see 309436-2021 (15 lots each lot has 15 contract periods)

See F25:

II.2.7.2 defines ContractPeriod hasBeginning exists in each lot as many times as there are lots instead of once for each lot see 303478-2021 (2 lots each lot has 2 contract periods)

**Comment by costezki** [comment]
1. contractTerm has multiple periods (not OK) should be a single one.

![image](https://user-images.githubusercontent.com/13567133/216026859-680fefcc-dc07-4500-9367-0ed38a435bd8.png)
![image](https://user-images.githubusercontent.com/13567133/216027168-61beddba-dbb3-4aa9-ba5c-5b1358508e61.png)

**Comment by csnyulas** [comment]
This has been fixed in commit f028b3541fade4e9cc79972dc3ae26f31b32c95e and it is part of the `tx1.4.beta` tag:
https://github.com/OP-TED/ted-rdf-mapping/blob/tx1.4.beta/mappings/package_F22/output/309436-2022/309436-2022.ttl
https://github.com/OP-TED/ted-rdf-mapping/blob/tx1.4.beta/mappings/package_F25/output/303478-2021/303478-2021.ttl
