### ISSUE TITLE
II.1.7.0 : Instantiation of a ContractAward element in a Contract Notice

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#318]
II.1.7.0 This field is instantiated in Contract Notice 371022-2021 however this field is only relevant to Contract Award Notices therefore it should not be instantiated

**Comment by csnyulas** [comment]
Closing this as it has been fixed both in the technical mapping (see referenced commits) as well as in the conceptual mapping (v.6.7.1)

![image](https://user-images.githubusercontent.com/2441046/219821544-c0d5047e-ee81-432b-a3ce-4b6a9492df6b.png)

In addition to not using `epo:announcesNoticeAwardInformation` property on notices that are not of type `epo:ResultNotice` (e.g. `epo:CompetitionNotice` or `epo:PlanningNotice`), we don't add this property also on Result Notices where the `epo:NoticeAwardInformation` is empty (i.e. there is no information to be shown because there is no `VAL_TOTAL` or `VAL_RANGE_TOTAL` value(s) specified).

BTW, related to https://github.com/OP-TED/ted-rdf-mapping/issues/318#issuecomment-1411908038 this has been fixed in tag `tx1.4.beta`, where the notice 371022-2021 was correctly classified as CompetitionNotice, as it can be seen also in the generated test output referenced above. However now we removed the reference to the empty `epo:NoticeAwardInformation`, which is not applicable for a competition notice.
