### ISSUE TITLE
Notice types and roles

### ISSUE THREAD

**Issue by muricna** [OP-TED/ted-rdf-mapping#320]
The ResultNotice inherits from Notice and not vice-versa therefore should it not be ResultNotice refersToRole?  This comment can be applied where ever the path is used.
The paths for other notice types and roles should also be checked and updated where necessary

**Comment by costezki** [comment]
This issue is about the signalling (in CM) and implementing the mapping (in TM) of relation choice link to the a role based on the Notice Type. 
1. Some roles are announced in ResultNotice and some other roles are referedTo. Winner is the ONLY role announced in the ResultNotice. (leave the Mediator and other "secondary roles" as are)
2. All roles are announced in the ContractNotice. 

This row needs to be duplicated and made conditional: one for "announces" and one for "refersTo".

![image](https://user-images.githubusercontent.com/13567133/216033908-631f1070-a448-49ca-aed4-1e1071cfa212.png)
![image](https://user-images.githubusercontent.com/13567133/216034684-80f2e227-3aa5-4489-ad9a-be1410e60e14.png)

**Comment by costezki** [comment]
We shall always `announce` because we do not know when we can `refer to`. 

For example:
We don't know what was `announced` before (in a previous notice) so that we can `refer to` it. 
Intuition says that a Buyer is announced in a CN and the same Buyer is referred to in a CAN. But this does not work when a CN is for the Framework Agreement (FA). There is a follow-up CAN referring to the same Buyers, but the CANs corresponding to the mini-competitions may use another set of buyers than the ones mentioned in the FA and so they have to `announce`.

**Comment by csnyulas** [comment]
Closing this as it was fixed both in technical mappings (see related commits above) and the conceptual mapping (starting with v.6.7.0)

![image](https://user-images.githubusercontent.com/2441046/219813112-5adb8cdb-8b48-4e8e-82ae-d72451344516.png)

**Comment by muricna** [comment]
This is correct as far as the ontology is concerned for the moment, but in the future this will need to be addressed.
