### ISSUE TITLE
Feedback F13 (issue 8, TM):  V.3.0.1 issue in number of tenders

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#357]
V.3.0.1 the number of Tenders in the notice should be equal to the number of winners in 410390-2021  there are 5 Winners but only one Tender (note there were 45 particpants)

**Comment by csnyulas** [comment]
There is no explicit XML element to represent the Tender(s) in the TED data (i.e. the XML representation of a notice). We use the `AWARD_CONTRACT/AWARDED_CONTRACT/`, and in case of F13 the `RESULTS/AWARDED_PRIZE` (which should be the logical equivalent of the "awarded contract") elements, as proxies for the tenders.
The logic here being that for each **awarded contract** (or in case of F13 **awarded prize**) there was one tender.  In other words, a contract, or a prize, is awarded based on a tender. _**Is this assumption correct?**_ @muricna could you please confirm this? 

With the above assumption, the mapping seems to be correct. There is only one Tender instance in the generated RDF, because there is only one `AWARDED_PRIZE` XML element in the `410390-2021.xml` file.

![image](https://user-images.githubusercontent.com/2441046/235709344-65e8e863-92db-4ac1-80cb-f309117d3052.png)

According to the XML, all five winners were awarded the same prize. For me this sounds like they had put in a tender together, and shared the prize. Can this be the case? Is there another, more logical explanation? If yes, what should be the XML element that we should use to identify the tenders? Please consider that the answer should make sense (i.e. be valid) for all the other forms as well.

**Comment by csnyulas** [comment]
Conclusion based on discussion with @muricna: 
In the case of F13 the "proxy" for the Tenders should be `RESULTS/AWARDED_PRIZE\WINNERS\WINNER`  or (`RESULTS/AWARDED_PRIZE\WINNER` for earlier XSD versions) not `RESULTS/AWARDED_PRIZE`, which does not seem to be a repeatable element like `AWARD_CONTRACT/AWARDED_CONTRACT`.

**Comment by csnyulas** [comment]
The solution has been verified and confirmed as correct. Here is an overview of the changes made in multiple commits for fixing this issue:
https://github.com/OP-TED/ted-rdf-mapping/compare/5bcae68...6d55774
