### ISSUE TITLE
Feedback F13 (issue 11, TM): V.3.2.3 Number of Tenders from other countries

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#360]
V.3.2.3 The field is number of Tenders from other countries doing a union will not help if the concept it refers to is epo:hasEUReceivedTenders.

**Comment by valexande** [comment]
Not sure that I totally understand what the problem is @csnyulas, but I will try to maybe point a sub case that came to my mind, and might be the problem addressed here.

Right now we have in our CM

{ ?this epo:hasEUReceivedTenders  ?value .  }
UNION
 { ?this epo:hasReceivedNonEUTenders ?value . }

Moreover, based on the definition we have from the glossary of ePO I can see

- epo:hasReceivedNonEUTenders is defined as "The amount of tenders received from economic operators in non-EU countries". 
- epo:hasEUReceivedTenders "The amount of tenders received from economic operators in other EU countries other than the country of the buyer".

If the country that recieves the Tenders is in EU then we should not have a problem as epo:hasEUReceivedTenders points to Tenders from different countries in EU. Similarly the property epo:hasReceivedNonEUTenders points to countries outside EU (and therefore different country) that are Tenders.

But the problem (if any) comes when the country which receives Tenders is outside EU, cause then the property epo:hasReceivedNonEUTenders does not state that the Tender which are from outside EU are on parallel from different country with the country that recieved the Tender. 

That is the only exception that come to my mind... :)

**Comment by csnyulas** [comment]
@valexande I also had difficulties understanding the issue, but after looking at the CM and the TM I think this is what @muricna means:

_Why would we have the UNION in the Property path field, if we only map to the `epo:hasEUReceivedTenders` property (and we don't map to the `epo:hasReceivedNonEUTenders` property)?_   (@muricna can confirm if this interpretation is correct.)

Part of the answer has to do with what you pointed out, @valexande, namely that both the `epo:hasEUReceivedTenders` and the `epo:hasReceivedNonEUTenders` properties refer to "other" countries (the first to other countries within EU, while the second to other countries outside the EU). 

The reason for which we had the UNION in the property path is, because we were not sure which is the most appropriate property to map to. In fact we mapped to both properties, but one mapping (to `epo:hasReceivedNonEUTenders`) was commented out. We should have probably clarified which one is the desired property to map to before the delivery, and adjust the CM accordingly. 

@muricna could you confirm that `epo:hasEUReceivedTenders` is the one, and only, correct property to map the `PARTICIPANTS/NB_PARTICIPANTS_OTHER_EU` XML element? Once this is confirmed, we can adjust the CM and TM.

**Comment by muricna** [comment]
I would suggest not mapping to this for the moment.  I will request the ontology to add an element for this.

**Comment by valexande** [comment]
Ok we will seperate the fields mapping. The Non-EU Tenders will be treated in a ticket (Issue #402)

**Comment by muricna** [comment]
What do you mean The Non-EU Tenders will be treated in a ticket.  Why are we talking about Non-EU Tenders? This is not used in F13.  It is tenders from other countries that is used.

**Comment by muricna** [comment]
ok with the explanation of the union written above we can keep it as it originally was
