### ISSUE TITLE
Feedback F23 CAN (issue 3, TM): IV.1.1.1 Interim solution is to map to procurement-procedure-type open

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#374]
IV.1.1.1:   See [Github 424](https://github.com/OP-TED/ePO/issues/424) for F25 which can also be applied for F23: A message has been sent to GROW, their interim solution is to map to procurement-procedure-type open.

**Comment by csnyulas** [comment]
This has been addressed as part of F25, both in the CM and in the TM (see issue #260).

Here is a screenshot from the relevant rows in the F23 CM:
![image](https://user-images.githubusercontent.com/2441046/235848870-f91ba56c-486b-436a-95e8-027bb82c45af.png)
Also this is the relevant line in the TM:
https://github.com/OP-TED/ted-rdf-mapping/blob/80738da924bd31ddc5669f4b3952d8b0d3009b19/src/mappings/s4_procedure.rml.ttl#L49

As mentioned in issue #260 (and in the Notes in the CM), this is a temporary solution until more appropriate values will be added by DG GROW. At that point issue #216 and #260, and this can be considered fully address and closed. We close this issue since any further changes to those two issues will automatically apply to this issue as well.
