### ISSUE TITLE
Feedback F23 CAN (issue 8, TM): V.0.4 Second line is considered superfluou

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#378]
V.0.4 (second lineà is considered superfluous as no Contract has been signed at this stage) Same comment for F25.

**Comment by csnyulas** [comment]
Change this mapping to refer to `epo:Lot` instead of `epo:Contract` and remove the additional type declaration `epo:ConcessionContract` (**specific for F23**):
![image](https://github.com/OP-TED/ted-rdf-mapping/assets/2441046/baa68b0a-2553-4a46-8f1e-ca25a8bc1078)

**Comment by csnyulas** [comment]
Closing this issue as it was fixed by updating the TM as can be seen in previous commits (basically we are not instantiating `epo:Contract` for F23 and F25). Master conceptual mapping was also updated to remove the second rdf:type (epo:ConcessionContract) from F23 and F25 contract instances (which won't exist anymore).

**Comment by csnyulas** [comment]
Updated CM also. This is how it looks the mapping of the head of section V. in version 2.1.1-beta.3 of the CM:

![image](https://github.com/OP-TED/ted-rdf-mapping/assets/2441046/95fd256a-2b3b-4682-ae0e-2ba64545ed6d)
