### ISSUE TITLE
Feedback F23 CAN (issue 9, CM): V.2.2 Two Xpaths

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#379]
V.2.2 For this section there are two xpaths in each row.

**Comment by csnyulas** [comment]
Indeed there are two XPATHs for each field in this section:
![image](https://user-images.githubusercontent.com/2441046/235862367-cb592266-f206-449a-b46a-e69eebb6a585.png)

The reason for this is to address differences in various XSD version (which was part of the TX1.4 delivery).

The technical mappings also written so that they can match XPATHs in XML notice data that was generated according to any current and previous XSD version:
![image](https://user-images.githubusercontent.com/2441046/235862041-5d40548f-aa54-4166-801b-3f7fcf31bfe2.png)

I do not see any problem here. In fact, AFAICT we are doing exactly the right thing.
@muricna can you please confirm?
Marked issue "for closing". We can close it as soon as we have confirmation from @muricna .

**Comment by muricna** [comment]
Please make sure this is documented somewhere

**Comment by valexande** [comment]
The issue was documented in the mapping remarks of the conceptual mapping, you can find it [here](https://docs.google.com/spreadsheets/d/1aF_gJ4bDzH0esYgjIzlGHhxL2lkNm-XmYjMYABNIjUU/edit#gid=408736519)
