### ISSUE TITLE
Feedback F23 CAN (issue 14, CM): VI.2.1-V.2.3 The predicate isSubjectToTerm is missing in CM

### ISSUE THREAD

**Issue by valexande** [OP-TED/ted-rdf-mapping#385]
VI.2.1-VI.2.3 The predicate isSubjectToTerm is missing in the conceptual mapping

**Comment by csnyulas** [comment]
Looking the second time at this issue, we are a bit confused about what exactly this problem/feature request is about.

If we look in EPO at the relationships that can be reated between `epo:Proecdure` (which is a subclass of `epo:ProcurementObject`) and the `epo:ContractTerm` (which is a subclass of `epo:ContractSpecificTerm` and therefore `epo:Term`) that has the `epo:hasEOrdering`, `epo:hasEPayment`, and `epo:hasEInvoicing` attributes, which are to be instantiated for fields VI.2.1-VI.2.3, one can see that both the `epo:foreseesContractSpecificTerm` and `epo:isSubjectToTerm` relationships can be used, the former, which is currently used, being more specific.


![image](https://github.com/OP-TED/ted-rdf-mapping/assets/2441046/3cc0f105-c45e-4ccf-842d-334197c7c6bc)


**@muricna could you please confirm what you would like here to be changed?** 
Would you like to have both relationships (`epo:foreseesContractSpecificTerm` and `epo:isSubjectToTerm`) added, to make querying easier? Or would you like `epo:foreseesContractSpecificTerm` replaced by `epo:isSubjectToTerm`? 
In either case, if we do this modification here, what about all the other places in the the mappings, where we use the most specific relations, for example `epo:isSubjectToLotSpecificTerm` or `epo:isSubjectToProcedureSpecificTerm`, instead of the more generic  `epo:isSubjectToTerm` relation. Should we replace them, or add `epo:isSubjectToTerm` relation, for those cases as well? That would be a huge undertaking.

**Comment by muricna** [comment]
The comment is about the conceptual mapping.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/muricna/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/muricna/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">

<style>

</style>
</head>

<body link="#1155CC" vlink="#1155CC">



VI.2.1 | Electronic ordering will be used | COMPLEMENTARY_INFO/EORDERING |   | epo:Procedure / epo:ContractTerm   / xsd:boolean | ?this epo:foreseesContractSpecificTerm / epo:hasEOrdering true . | VI.2.1-V.2.3 The predicate   isSubjectToTerm is missing in the conceptual mapping     None of the elements available in sample |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
VI.2.2 | Electronic invoicing will be   accepted | COMPLEMENTARY_INFO/EINVOICING |   | epo:Procedure / epo:ContractTerm   / xsd:boolean | ?this   epo:foreseesContractSpecificTerm / epo:hasEInvoicing true . |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
VI.2.3 | Electronic payment will be used | COMPLEMENTARY_INFO/EPAYMENT |   | epo:Procedure / epo:ContractTerm   / xsd:boolean | ?this   epo:foreseesContractSpecificTerm / epo:hasEPayment true . |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  



</body>

</html>
